services:
  db:
      image: mysql:8.0
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sample_app_development
          MYSQL_USER: user
          MYSQL_PASSWORD: password
      ports:
          - '3306:3306'
      volumes:
          - mysql_volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOSTS=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "9999:80"
  web:
      build:
          context: .
          dockerfile: Dockerfile.develop  # 最初に作成したDockerfileを指定
      ports:
          - '3000:3000'
      stdin_open: true
      tty: true  # コンテナを起動させ続ける
      depends_on:
          - db
      volumes:
          - .:/app

volumes:
    mysql_volume: